---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: service-user
  namespace: service
spec:
  replicas: 1
  selector:
    matchLabels:
      type: service
      for: user
  template:
    metadata:
      labels:
        type: service
        for: user
    spec:
      containers:
        - name: user
          image: argoproj/rollouts-demo:blue
          #image: argoproj/rollouts-demo:green
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 200m
              memory: 512Mi
  strategy:
    blueGreen:
      activeService: service-user-active
      previewService: service-user-preview
      autoPromotionEnabled: false
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: service-products
  namespace: service
spec:
  replicas: 1
  selector:
    matchLabels:
      type: service
      for: products
  template:
    metadata:
      labels:
        type: service
        for: products
    spec:
      containers:
        - name: products
          image: argoproj/rollouts-demo:blue
          #image: argoproj/rollouts-demo:green
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 1
              memory: 1024Mi
            limits:
              cpu: 1
              memory: 1024Mi
  strategy:
    blueGreen:
      activeService: service-products-active
      previewService: service-products-preview
      autoPromotionEnabled: false
