---
kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-active
  namespace: service
spec:
  type: ClusterIP
  selector:
    app: rollout-bluegreen
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-preview
  namespace: service
spec:
  type: ClusterIP
  selector:
    app: rollout-bluegreen
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
