---
apiVersion: v1
kind: Service
metadata:
  name: service-user-active
  namespace: service
spec:
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 31081
  selector:
    for: user
    type: service
---
apiVersion: v1
kind: Service
metadata:
  name: service-user-preview
  namespace: service
spec:
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 31082
  selector:
    for: user
    type: service
---
apiVersion: v1
kind: Service
metadata:
  name: service-products-active
  namespace: service
spec:
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 31083
  selector:
    for: products
    type: service
---
apiVersion: v1
kind: Service
metadata:
  name: service-products-preview
  namespace: service
spec:
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 31084
  selector:
    for: products
    type: service
