apiVersion: v1
data:
  service.webhook.server-post-prod: |
    url: http://localhost:9097
    headers: #optional headers
    - name: Content-Type
      value: application/json; charset=utf8
    insecureSkipVerify: true #optional bool
  template.server-post-prod-on-sync-failed: |
    webhook:
      server-post-prod:
        method: POST # one of: GET, POST, PUT, PATCH. Default value: GET
        path: /api/ext/push/send
        body: |
         {
            "title": "ArgoCD Notification",
            "message": "{{.app.spec.source.targetRevision}}|{{.app.metadata.name}}\n App Health Status : {{.app.status.health.status}}\n App Sync Status : {{.app.status.sync.status}}\n App OperationState Phase : {{.app.status.operationState.phase}}",
            "pushType": "2",
            "userId": ["L"],
            "senderCode": "admin"
         }
  trigger.on-sync-failed: |-
    - description: Application syncing has failedsend
      send:
      - server-post-prod-on-sync-failed
      when: app.status.operationState.phase in ['Error', 'Failed'] or app.status.health.status in ['Degraded', 'Missing', 'Unknown'] or app.status.sync.status in ['OutOfSync', 'Unknown', 'Synced']
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: openshift-gitops
