apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notification-cm
  namespace: argocd
data:
  service.webhook.server-post-prod: |
    url: http://example.com
    headers: #optional headers
    - name: Content-Type
      value: application/json; charset=utf8
    insecureSkipVerify: true #optional bool
  template.server-post-prod-on-sync-failed: |
    webhook:
      server-post-prod:
        method: POST
        path: /api/send
        body: |
          {
            "title": "ArgoCD Notification",
            "message": "PP.app.spec.source.targetRevision}}-{{.app.metadata.name}}, {{.app.status.health.status}"
          }
  trigger.on-sync-failed: |-
    - description: Application syncing has failed
      send:
      - server-post-prod-on-sync-failed
      when: app.status.operationState.phase in ['Error', 'Failed'] or app.status.health.status in ['Degraded', 'Mission', 'Unknown']
