apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.webhook.server-post-prod: |
    url: https://mattermost.itapi.org
    headers: #optional headers
    - name: Content-Type
      value: application/json
    insecureSkipVerify: true #optional bool
  template.server-post-prod-on-sync-failed: |
    webhook:
      server-post-prod:
        method: POST # one of: GET, POST, PUT, PATCH. Default value: GET
        path: /hooks/7qpcj3h6o3rsmppb75ew4hg9pw
        body: |
         {
            "text": "{{.app.spec.source.targetRevision}}|{{.app.metadata.name}}\n App Health Status : {{.app.status.health.status}}\n App Sync Status : {{.app.status.sync.status}}\n App OperationState Phase : {{.app.status.operationState.phase}}",
            "attachments": [
                {
                    "fallback": "test",
                    "color": "#FF8000",
                    "pretext": "This is optional pretext that shows above the attachment.",
                    "text": "This is the text of the attachment. It should appear just above an image of the Mattermost logo. The left border of the attachment should be colored orange, and below the image it should include additional fields that are formatted in columns. At the top of the attachment, there should be an author name followed by a bolded title. Both the author name and the title should be hyperlinks.",
                    "author_name": "Mattermost",
                    "author_icon": "https://mattermost.com/wp-content/uploads/2022/02/icon_WS.png",
                    "author_link": "https://mattermost.org/",
                    "title": "Example Attachment",
                    "title_link": "https://developers.mattermost.com/integrate/reference/message-attachments/",
                    "fields": [
                        {
                            "short":false,
                            "title":"Long Field",
                            "value":"Testing with a very long piece of text that will take up the whole width of the table. And then some more text to make it extra long."
                        },
                        {
                            "short":true,
                            "title":"Column One",
                            "value":"Testing"
                        },
                        {
                            "short":true,
                            "title":"Column Two",
                            "value":"Testing"
                        },
                        {
                            "short":false,
                            "title":"Another Field",
                            "value":"Testing"
                        }
                    ],
                    "image_url": "https://mattermost.com/wp-content/uploads/2022/02/icon_WS.png"
                }
            ]
         }
  trigger.on-sync-failed: |-
    - description: Application syncing has failedsend
      send:
      - server-post-prod-on-sync-failed
      when: app.status.operationState.phase in ['Error', 'Failed'] or app.status.health.status in ['Degraded', 'Missing', 'Unknown'] or app.status.sync.status in ['OutOfSync', 'Unknown', 'Synced']
